CHANGES.rst, plone/schemaeditor/browser/schema/listing.py, plone/schemaeditor/browser/schema/schema_listing.pt, plone/schemaeditor/fields.py, plone/schemaeditor/interfaces.py
`protected()` will return `False` by default, but by overriding it in a custom subclass, we can get the same rendering as a behavior field (= not editable and not draggable) for any field we want.
=> Add a "protected" method to IFieldFactory

CHANGES.rst, plone/schemaeditor/browser/schema/add_field.py
Extra fields providing IFieldEditorExtender are displayed in the field Add form, and the submitted values are stored in the newly created instance.
Note: I am not very confident about my changes in the `FieldAddForm.create` method, if anybody having a good knowledge of this module (@davisagli or @tdesvenain maybe?), it would be nice.
=> Supports additionalSchemata in field Add form 

plone/schemaeditor/browser/field/edit.pt, plone/schemaeditor/browser/field/edit.py, plone/schemaeditor/browser/schema/add.pt, plone/schemaeditor/browser/schema/add_field.py, plone/schemaeditor/browser/schema/add_fieldset.py, plone/schemaeditor/configure.zcml, plone/schemaeditor/tests/choice.txt, plone/schemaeditor/tests/editing.txt, plone/schemaeditor/tests/minmax.txt
@vangheem @davisagli : it appears we could not safely remove modals here (too many technical + UI consequences). So here is my fix:
- messages that must be displayed in the parent window are produced using `Products.statusmessages`, messages that must appear in the modals are still produce using `self.status`,
- after adding or editing a field, we do not redirect to parent (that would burn the status messages), as the modal will reload the parent window anyway,
- we do not use the main template anymore to display add and edit forms, so it does not burn the `Products.statusmessages` messages.
@tisto, 2 bad news for you:
- we keep the modals,
- it does break the tests in p.a.users, p.a.dexterity and p.schemaeditor because it seems the BrowserTest requests cannot be adapted to create portal …
=> Display status message in parent window after modal close

CHANGES.rst, plone/schemaeditor/browser/schema/listing.py
Make ``plone.protect.utils.addTokenToUrl`` a soft dependency, making this package usable in Plone < 5.0.
=> addTokenToUrl soft dependency 2nd try

CHANGES.rst, plone/schemaeditor/__init__.py, plone/schemaeditor/browser/configure.zcml, plone/schemaeditor/browser/field/configure.zcml, plone/schemaeditor/browser/field/edit.py, plone/schemaeditor/browser/schema/add_field.py, plone/schemaeditor/browser/schema/add_fieldset.py, plone/schemaeditor/browser/schema/configure.zcml, plone/schemaeditor/browser/schema/listing.py, plone/schemaeditor/browser/schema/schema_listing.pt, plone/schemaeditor/configure.zcml, plone/schemaeditor/fields.py, plone/schemaeditor/fields.zcml, plone/schemaeditor/interfaces.py, plone/schemaeditor/locales/update.sh, plone/schemaeditor/schema.py, plone/schemaeditor/tests/editing.txt, plone/schemaeditor/tests/robot_testing.zcml
plone.schemaeditor is an official Plone core package,
thus their translations belong to plone.app.locales.
This commit removes the plone.schemaeditor domain and changes it for
plone.
This fixes:
https://github.com/plone/plone.schemaeditor/issues/34
Note that this needs to be merged together with a pull request on plone.app.dexterity as both packages depend on each other when it comes to translations.
=> Use plone i18n domain

CHANGES.rst, plone/schemaeditor/browser/schema/schema_listing.pt, plone/schemaeditor/browser/schema/schemaeditor.js, plone/schemaeditor/configure.zcml, plone/schemaeditor/testing.py, plone/schemaeditor/tests/browser_testing.zcml, plone/schemaeditor/tests/choice.txt, plone/schemaeditor/tests/fixtures.py, plone/schemaeditor/tests/robot_testing.zcml, setup.py
These fixes allow use of plone.schemaeditor on Plone 4 sites using either/both plone.protect 3.x and/or plone.app.widgets 1.x (with mockup 2).
These fixes are IMHO important enough to justify a 1.3.12 release.
=> 1.3.x compatibility backports; with both mockup 2.x and plone.protect 3.x

CHANGES.rst, plone/schemaeditor/browser/schema/schemaeditor.js
I accidentally removed prepOverlay calls needed in Plone 4 schema editor in my backport of the JavaScript from Plone 5's schema editor (master) backport in my commit 8774cddaf1079eea3cda805c62f5cbdf7e0ff68e
This PR fixes that accidental removal.
=> Fix accidental removal of overlay handlers (fixes regression in 1.4)

CHANGES.rst, plone/schemaeditor/browser/field/edit.py, plone/schemaeditor/browser/schema/add_field.py, plone/schemaeditor/browser/schema/schemaeditor.js, plone/schemaeditor/fields.py, plone/schemaeditor/interfaces.py, plone/schemaeditor/tests/fixtures.py, plone/schemaeditor/tests/tests.py, plone/schemaeditor/utils.py
This PR fixes the URL for the reordering and changing fieldsets. It removes the query_string from the base part of the URL.
Before:
http://localhost:8080/Plone/a-form/fields/topic/?authenticator=075c08f07c45ce137c77f6be5c422c2041587407/@@order 
Now:
http://localhost:8080/Plone/a-form/fields/topic/@@order 
(the authenticatior is in the POST)
Test with collective.easyform.
=> Fix URL for reordering fields

CHANGES.rst, plone/schemaeditor/browser/field/fieldset.py, plone/schemaeditor/browser/schema/add_field.py, plone/schemaeditor/browser/schema/schemaeditor.js, plone/schemaeditor/tests/robot/test_fields.robot, plone/schemaeditor/utils.py
- Fix Schemaeditor fields editing UI to be able to move fields into another fieldset.
- Cleanup: Remove Plone 4 related form tabbing CSS selectors from fields editing UI JavaScript.
- JavaScript formating according to style guides.
Fixes:
- https://github.com/plone/plone.schemaeditor/issues/30
- https://github.com/collective/collective.easyform/issues/50
Merge all of these:
- https://github.com/plone/plone.schemaeditor/pull/54
- https://github.com/plone/mockup/pull/763
- https://github.com/plone/Products.CMFPlone/pull/2045
=> fix schemaeditor fields editing UI

CHANGES.rst, plone/schemaeditor/fields.py, plone/schemaeditor/tests/test_fields.py, plone/schemaeditor/tests/tests.py
Allow specifying a vocabulary in the form of *key|label* in (multi)choice fields as seen at PFG.
=> Manage simple "vocabularies" in the values field

CHANGES.rst, plone/schemaeditor/browser/schema/schemaeditor.js
Fix fields not being reorderable and missing their delete confirmation until a fieldset was added.
Fixes https://github.com/collective/collective.easyform/issues/81 and https://github.com/collective/collective.easyform/issues/82
=> Field reorderable, missing delete confirmation

CHANGES.rst, plone/schemaeditor/fields.py
This bug was introduced with
https://github.com/plone/plone.schemaeditor/commit/dbfe9541b032ea62282d5facc5216ec7283d0715
and results in
https://github.com/collective/collective.easyform/issues/96
=> Fix getting vocabulary for multichoice fields

news/71.bugfix, plone/schemaeditor/browser/schema/listing.py
Also added a "Done" button that leaves the field edit view.
Refs #71
=> Ignore validation errors for "required" when saving defaults

news/69.feature, plone/schemaeditor/browser/schema/configure.zcml, plone/schemaeditor/browser/schema/delete_fieldset.py, plone/schemaeditor/browser/schema/schema_listing.pt, plone/schemaeditor/tests/editing.rst
Allows deleting empty fieldsets.
Why only empty ones? It seems a bit risky to delete all contained fields because there is no undo. Besides, I can't think of a use case where I wanted to delete a whole fieldset including all its fields. The main use case is probably that a fieldset becomes obsolete because all fields have been deleted or move to another one anyway. As long as there's no possibility to edit a fieldset this can also serve as a workaround for renaming - create a new fieldset, move over the fields, delete the old one.
Refs #69
=> Added "Delete fieldset" functionality

news/66.bugfix, plone/schemaeditor/tests/robot/test_fields.robot
I'm in the process of trying to unify Robot test setups and teardowns. This is a part of that effort.
Also re-enabled two previously disabled Robot tests.
In tandem with plone/plone.app.robotframework#110
Closes https://github.com/plone/plone.schemaeditor/issues/66
I also tried to revive the commented out tests, but those are just badly done and would require a rewrite. Despite tackling the stability of the Robot tests, I'm not actually well versed enough in Robot itself or the schema editor to try to redo those tests.
=> Default to a 4K x 4K browser window in Robot tests

plone/schemaeditor/tests/robot/test_fields.robot
This test fails randomly. Sometimes the keyword doesn't give an error but doesn't do what it should. Now, in case of an error, we try again.
This try fix:
```bash
==============================================================================
Test Fields                                                                   
==============================================================================
Add a choice field with a named vocabulary                            | FAIL |
Element 'css=div[data-field_id="languages"] a.fieldSettings' did not appear in 30 seconds.
------------------------------------------------------------------------------
Test Fields                                                           | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed …
```
=> Makes test Add a choice field with a named vocabulary more robust

plone/schemaeditor/tests/robot/test_fields.robot
Use the correct selector to check for the overlay: it is no longer `div.overlay`, but `div.modal-wrapper`.
Wait only 8 seconds instead of 60 for this check to be true.
Also use 'Wait For Then Click Element' for good measure.
This is an attempt to make robot tests more stable
I still sometimes see a test fail, becase the popup/modal/overlay is still open after clicking a button.  This might fix it.
Update: no it does not.  But the updated checks at least make it clear that a popup is still open, which is the reason why some other expected text is not visible.
Sample from "Capture Page Screenshot" for a failed test:
This looks exactly like I expect it to, except that the modal should have closed because the button has been clicked.
=> Robot tests: wait until overlay is closed.

news/93.bugfix, plone/schemaeditor/interfaces.py, plone/schemaeditor/tests/editing.rst
According to the regular expression, a field must start with a lowercase character.
I am not sure this is really needed.  But now the validation error matches the expression.
I got a question from a customer about this.
=> Fix incomplete validation error for invalid field name.

news/86.bugfix, plone/schemaeditor/browser/schema/add_field.py, plone/schemaeditor/browser/schema/add_fieldset.py, plone/schemaeditor/browser/schema/listing.py, plone/schemaeditor/browser/schema/schema_listing.pt, plone/schemaeditor/interfaces.py, plone/schemaeditor/tests/robot/test_fields.robot, plone/schemaeditor/utils.py
=> Fix adding and moving fields between fieldsets.

news/3582.bugfix, plone/schemaeditor/tests/robot/test_fields.robot
Tests fail too often here, having the modal still open after clicking this button.
See https://github.com/plone/Products.CMFPlone/issues/3582
=> Tests: sleep before clicking button to add new content type.

news/+autotoc.tests.md, plone/schemaeditor/tests/robot/test_fields.robot
see https://github.com/plone/mockup/pull/1479
NOTE: the tests handle both implementations so it doesn't depend on the merged staticresources PR
=> Fix robottests for new autotoc implementation
